OBJECT_WORDS = [
    "Thing",
    "Article",
    "Body",
    "Commodity",
    "Item",
    "Matter",
    "Phenomenon",
    "Something",
    "Substance",
    "Bulk",
    "Do-dad",
    "Do-hickey",
    "Entity",
    "Gizmo",
    "Mass",
    "Thing-ah-ma-jig",
    "What-cha-ma-call-it"
]
