SCARY_WORDS = [
    "Scary",
    "Frightening",
    "Very scary",
    "Terrifying",
    "Alarming",
    "Daunting",
    "Frightful",
    "Grim",
    "Harrowing",
    "Shocking",
    "Chilling",
    "Creepy",
    "Eerie",
    "Hairy",
    "Horrifying",
    "Intimidating",
    "Spooky",
    "Bloodcurdling",
    "Hair-raising",
    "Horrendous",
    "Spine-chilling",
    "Unnerving",
    "Spoopy",
]
