SWEAR_WORDS = [
    "Balderdash!",
    "Corn Nuts!",
    "Dag-nab-bit!",
    "Barnacles!",
    "Holy cow!",
    "O M G!",
    "Poo on a stick!",
    "Sugar!",
    "Judas Priest!",
    "Sufferin succatash!",
    "God bang it!",
    "Oh snap!",
    "Great Scott!",
    "Bullspit!",
    "Leeping lizards!",
    "Cheese and crackers!",
    "Frack me!",
    "W T F!",
    "Crappity crap!",
    "Shi-tar-key mushrooms!",
    "Fraggle Rock!",
    "Shut the front door!",
    "Son of a gun!",
    "Son of a monkey!",
    "Son of a biscuit!",
    "Ee-gads!",
    "Gad zooks!",
    "Barbra Streisand!",
    "Shnikes!",
    "Shanig-its!",
    "Jumpin Jehhosaphat!",
    "Mother trucker!",
    "Crikey!",
    "Peas and rice!",
    "Jeepers!",
    "Blimey!",
    "Galloping gremlins!",
    "Oh ship!",
    "Toemato paste!",
    "Squeak!",
    "Zoinks!",
    "Fart knocker!",
    "Merlin's beard!",
    "Holy guaca-moly!",
    "Oh coconuts!",
    "Drat!",
    "Ay ca-rum-ba!",
    "What the cuss?",
    "Fudging heck!",
    "Fudge nuggets!",
    "Butt nuggets!",
    "Bananarama!",
    "Frick!",
    "Butt cheeks!",
    "Mother hubbad!",
    "Christ on a bike!",
]
