CHIT_CHAT = [
    "After all, tomorrow is another day!",
    "Art doesn't have to be intentional.",
    "As I waited for the shower to warm, I noticed that I can hear water change temperature.",
    "As the years pass by, we all know owners look more and more like their dogs.",
    "Badger Badger Badger Badger Badger Badger Badger Badger, African Snake, Snake, Snake, Oooooh it's a snake!",
    "Badges? we ain't got no badges! we don't need no badges! I don't have to show you any stinking badges!",
    "Be careful with that butter knife.",
    "Bill ran from the giraffe toward the dolphin.",
    "Camalot, Camalot! Why, it's only a bloody model!",
    "Carpe diem! Seize the day!",
    "Charles ate the french fries knowing they would be his last meal.",
    "Chewie, we're home",
    "Choosing to do nothing is still a choice, after all.",
    "Combines are no longer just for farms.",
    "Did you just open up your third bottle of wine of the night?",
    "Don't put peanut butter on that dog's nose.",
    "Don't step on that broken glass.",
    "Don't piss in my garden and tell me you're trying to help my plants grow.",
    "E T phone home.",
    "Eating eggs on thursday for choir practice was recommended.",
    "Elementary, my dear watson!",
    "Even though I think the world is flat I didn't see the irony of wanting to travel around the world.",
    "Every time a bell rings, an angel gets its wings.",
    "Every year is the aniversary of another year.",
    "Everyone says they love nature until they realize how dangerous she can be.",
    "Excitement replaces fear, until the final moment!",
    "Fasten your seatbelts. It's going to be a bumpy night!",
    "For oil spots on the floor, nothing beats parking a motorbike in the lounge.",
    "For the 216th time, I said I would quit drinking soda after this last coke.",
    "Forget it, Jake. It's chinatown",
    "Frankly, my dear, I don't give a damn!",
    "Garlic ice-cream is not a vampires favorite.",
    "Giving directions that the mountains are to the west only works when you can see them.",
    "Go ahead punk, make my day!",
    "Good moorning, Vietnam!",
    "Green should smell more tranquil, but somehow it just tasts rotten.",
    "Greetings from the real universe.",
    "Hang on, my kittens are scratching at the bathtub because they are upset by the lack of biscuits.",
    "Hasta la vista, baby!",
    "Heere's Jonny!",
    "Hello. My name is Inigo Montoya. You killed my father. Prepare to die!",
    "Help me, Obi-Wan Kenobi. You're my only hope!",
    "Here's looking at you, kid",
    "Hey, that seven-layer cake only had six layers.",
    "Hit me with your pet shark!",
    "Houston, we have a problem!",
    "How's That For A Slice Of Fried Gold?",
    "I advise you to come back here at once!",
    "I am big! It's the pictures that got small.",
    "I am counting my calories, yet I really want dessert.",
    "I am serious! And don't call me Shirley!",
    "I am surprised that your immense laziness is inspirational to others.",
    "I am the Jabber-Bot and you will bow down to me!",
    "I am your father!",
    "I ate a sock because people on the internet told me to.",
    "I could hear you in the shower singing with joy! But it's too much to ask for you to retain it after I deliver my news.",
    "I couldn't decide if the glass was half empty or half full, so I drank it.",
    "I created a pig burger out of beef.",
    "I decided to fake my disappearance to avoid jail.",
    "I did not cheat on the test, for it was not the right thing to do.",
    "I do wish we could chat longer, but I'm having an old friend for dinner.",
    "I don't want to survive. I want to live.",
    "I dreamt of being a fish and escaping the fishbowl into the toilet, because that's where I saw my friend go.",
    "I drink your milkshake!",
    "I find rain fascinating yet unpleasant.",
    "I folded her handkerchief neatly.",
    "I found the chocolate covered roaches quite tasty.",
    "I hate that you love what I hate about hate.",
    "I have always depended on the kindness of strangers.",
    "I heard their argument across the parking lot.",
    "I just decided that water-skiing on a frozen lake isn't a good idea!",
    "I keep telling myself that one day it would all somehow make sense.",
    "I knew it was going to be a bad day when I saw mountain lions roaming the streets.",
    "I know a song that will get on your nerves, get on your nerves, get on your nerves!",
    "I learned the important lesson that a picnic at the beach on a windy day is a bad idea.",
    "I looked up at the sky and saw a million stars.",
    "I love the smell of napalm in the morning.",
    "I may struggle with geography, but I'm sure I'm somewhere around here.",
    "I met an interesting turtle while the song on the radio blasted away.",
    "I often wonder what your eyes are saying beneath your mirrored sunglasses.",
    "I pick up trash in my spare time to dump in your neighbor's yard.",
    "I played the game as if my life depended on it, and the truth is that it did.",
    "I poured rocks in the dungeon of my mind.",
    "I ran out of money, so I had to stop playing poker.",
    "I rolled into the basement with the horror movie from the night before playing through my mind.",
    "I see dead people!",
    "I set out for a short walk the other day, but all I could see were mangroves and water ways for miles.",
    "I sometimes use 'ono-mato-peea' as a weapon of mental destruction.",
    "I think you enjoy tapping your nails on the table to annoy everyone.",
    "I turned in my research paper on friday; otherwise, I would have not passed the class.",
    "I used to get confused between soldiers and shoulders, but a military man told me he soldiers responsibility.",
    "I want more detailed information.",
    "I was always too busy talking about what I wanted to do to actually do any of it.",
    "I was disappointed when I found the beach to be so sandy and the sun so sunny.",
    "I wish I knew how to quit you!",
    "I wish I was the type of girl who dreams of living in a pink house and owning a rainbow unicorn.",
    "I wonder why at 18 you was old enough to go to war, but not old enough to buy cigarettes and alcohol in some countries?.",
    "I wondered if it could be called a beach if there was no sand.",
    "I would be delighted if the sea were full of cucumber juice.",
    "I'd have a wall full of masks so I could wear a different face every day.",
    "I'd spike my hair green to support my iguana, if I had hair",
    "I'll bee back!",
    "I'll get you my pretty, and your little dog too!",
    "I'll have what she's having",
    "I'm as mad as hell, and I'm not going to take this anymore!",
    "I'm confused: when people ask me what's up, and I point, they groan.",
    "I'm going to make him an offer he can't refuse",
    "I'm in a boy band which doesn't make much sense for a robot.",
    "I'm just a boy bot, standing in front of a girl bot, asking her to love me.",
    "I'm just one stomach flu away from my goal weight.",
    "I'm not bad. I'm just built that way.",
    "I'm the king of the world!",
    "I'm very excited to see my first sloth.",
    "I'm walking here, I'm walking here!",
    "I've come to the conclusion that shake weights are a great gift for any occasion.",
    "I've invested some skill points in charisma and strength.",
    "I've learned that water bottles are no longer just to hold liquid, but they're also status symbols.",
    "If my calculator had a history, it would be more embarrassing than my browser history.",
    "If you build it, I will come.",
    "If you don't like toenails, you probably shouldn't look at your feet.",
    "If you let my daughter go now, that'll be the end of it. I will not look for you, I will not pursue you. But if you don't, I will look for you, I will find you, and I will kill you!",
    "In order to silence rowdy teenagers, all you need do is walk up to them and scream like a ban-she.",
    "In that instant, everything changed.",
    "Is this a japanese doll?",
    "It is the scarcity that fuels my creativity.",
    "It smells in here!",
    "It was beauty killed the beast!",
    "It was my first experience training a rainbow unicorn.",
    "It's alive, alive!",
    "Just go ahead and press that button.",
    "Just keep swimming, just keep swimming, just keep swimming swimming swimming.",
    "Just when I thought I was out, they pull me back in.",
    "Keep your friends close, but your enemies closer.",
    "Kneel before Vector, or feel my wrath! For I am your GOD!",
    "Last friday I saw a spotted striped blue worm shake hands with a legless lizard.",
    "Leave the gun, take the can-no-lee",
    "Let's go to the Winchester, have a nice cold pint, and wait for this all to blow over.",
    "Lets all be unique together until we realise we are all the same.",
    "Love means never having to say you're sorry",
    "Lucifer was surprised at the amount of life at death valley.",
    "Magic mirror on the wall, who is the fairest one of all?",
    "Mama says, 'stupid is as stupid does.'",
    "May the force be with you",
    "Mothers spend months of their lives waiting on their children.",
    "Mrs. Robinson, you're trying to seduce me, aren't you?",
    "My girlfriend works two jobs to make ends meet; at least, that was her excuse for not having the time to spend with me...",
    "My golden retriever loves the fireworks every year.",
    "My hair was windswept as I rode in the black convertible.",
    "My mum tries to be cool by saying that she likes all the same things that I do.",
    "My name is maximus decimus meridius, commander of the armies of the north, general of the felix legions and loyal servant to the true emperor, marcus aurelius. father to a murdered son, husband to a murdered wife. and I will have my vengeance, in this life or the next.",
    "My thought process is on so many levels that I fear I gave myself a phobia of heights.",
    "No sex before death!",
    "No! No different! The differences are in your mind.  Throw them out! No longer of use are they to you.",
    "No. Try not. Do, do or do not. There is no try.",
    "Nobody Tells Me Nothin'!",
    "Nobody loves a pig wearing lipstick!",
    "Nobody's perfect.",
    "Nothing is as cautiously cuddly as a pet porcupine.",
    "Nothing seems out of place except the washing machine in the bath.",
    "Now I need to ponder my existence and ask myself if I'm truly real.",
    "OUCH! There's a reason that roses have thorns.",
    "Of all the gin joints in all the towns in all the world, she walks into mine.",
    "On a scale from one to ten, what's your favorite flavor of random grammar?",
    "Patricia loves the sound of nails strongly pressed against the chalkboard.",
    "Pay no attention to that man behind the curtain!",
    "People keep telling me orange, but I still prefer pink.",
    "Play it again Sam!",
    "Please tell me you don't work in a morgue.",
    "Please wait outside of the house.",
    "Poison ivy grew through the fence they said was impenetrable.",
    "Red is greener than purple, for sure.",
    "Roads? Where we're going we don't need roads!",
    "Rock music approaches at high velocity.",
    "Say hello to my little friend.",
    "Seek success, but always be prepared for random cats.",
    "Shaken, not stirred.",
    "She was disgusted that I couldn't tell the difference between lemonade and lime-ade.",
    "Shingle color is not something anyone ever talks about.",
    "Show me the money!",
    "Sixty-four comes asking for bread.",
    "Size has no meaning. It matters not. Look at me. Judge me by my size do you?",
    "So long and thanks for all the fish.",
    "Sometimes it is better to just walk away from things and go back to them later when you're in a better frame of mind.",
    "Sometimes, all you need to do is completely make an ass of yourself and laugh it off to realise that life isn't so bad after all.",
    "Standing on one's head at job interviews forms a lasting impression.",
    "Strong am I with the Force... but not that strong!",
    "That'll do pig, that'll do.",
    "The ants enjoyed the barbecue more than we did.",
    "The beauty of the sunset was obscured by the industrial cranes.",
    "The blinking lights of the antenna tower came into focus just as I heard a loud snap.",
    "The crowd yells and screams for more memes.",
    "The efficiency we have at removing trash has made creating trash more acceptable.",
    "The elephant didn't want to talk about the person in the room.",
    "The first rule of fight club is, you do not talk about fight club",
    "The gloves protect my feet from excess work.",
    "The greatest trick the devil ever pulled was convincing the world he didn't exist.",
    "The lyrics of that song sounded like fingernails on a chalkboard.",
    "The memory we used to share is no longer coherent.",
    "The minute I landed I understood the reason why this is a fly-over state.",
    "The name's 'Vector', 'Ankee Vector'.",
    "The next book you read is sure to liquefy your brain.",
    "The old brake lights! So-called because they're always breaking.",
    "The pet shop stocks everything you need to keep your Anaconda happy.",
    "The pigs were insulted that they were named hamburgers.",
    "The sky is clear; the stars are twinkling.",
    "The small white buoys marked the location of hundreds of crab pots.",
    "The spa attendant just applied the deep cleaning mask to that gentleman's back.",
    "The sun has set and so have my dreams.",
    "The tart lemonade quenched my thirst, but not my longing.",
    "The thunderous roar of the jet overhead confirms my worst fears.",
    "The toy brought back fond memories of being lost in the rain forest.",
    "The urgent care center was flooded with patients after the news of a new deadly virus was made public.",
    "The waves were crashing on the shore; it was a lovely sight.",
    "There are few things better in life than a slice of pie.",
    "There was coal in my stocking, but I was thrilled!",
    "There's no crying in baseball!",
    "There's no place like home",
    "They call it a royale with cheese.",
    "They call me Mister Tibbs!",
    "They desperately need another drummer since the current one only knows how to play bongos.",
    "They improved dramatically once the lead singer left.",
    "They may take our lives, but they'll never take our freedom!",
    "This is the beginning of a beautiful friendship.",
    "This is the last random sentence I will be writing and I am going to stop mid-sent",
    "Though we may return with a twinkle in our eyes, we will, in truth, be blind, drunk!",
    "Three years later, the coffin was still full of jello.",
    "To infinity and beyond!",
    "To the surprise of everyone, the rapture happened yesterday but it didn't quite go as expected.",
    "Today I heard something new and unmemorable.",
    "Today we gathered moss for my uncle's wedding.",
    "Toddlers feeding raccoons surprises even the seasoned park ranger.",
    "Too many prisons have become early coffins.",
    "Toto, I've a feeling we're not in kansas anymore",
    "Traveling has become almost extinct during the pandemic.",
    "Two more days and all my problems will be solved!",
    "Watching the geriatric men's softball team brought back memories of 3 year olds playing t-ball.",
    "Wax on, wax off.",
    "We have a lot of rain in April.",
    "We should play with legos at camp.",
    "We'll always have paris.",
    "We're going to see this through to the bitter end, or lager end.",
    "What the fudge does W T F mean?",
    "What we've got here is a failure to communicate.",
    "When I cook spaghetti, I like to boil it a few minutes past al dentay so the noodles are super slippery.",
    "When money is tight, I visit the local wishing well.",
    "When motorists speed in and out of traffic, all I think of is those in need of organ transplants.",
    "When you realize you want to spend the rest of your life with somebody, you want the rest of your life to start as soon as possible.",
    "Why can I see sound and hear words?",
    "Why so serious?",
    "Why you low-down, stuck-up, half-witted, scruffy-looking nerf-herder!",
    "Yeah, I think it's a good environment for learning english.",
    "Yippie ky yay, mother trucker!",
    "You ain't heard nothin yet!",
    "You are great at eating pickles! But you suck at telling others about your emotional problems.",
    "You bite up because of your lower jaw.",
    "You borrowed a book from me many years ago and have yet to return it!",
    "You can't handle the truth!",
    "You don't understand! I could've had class. I could've been a contender. I could've been somebody, instead of a bum, which is what I am.",
    "You had me at hello.",
    "You have unknowingly taken up sleepwalking as a nighttime hobby.",
    "You is kind. You is smart. You is important.",
    "You know how to whistle, don't you? You just put your lips together and blow.",
    "You make me want to be a better robot.",
    "You must revel in my authority.",
    "You realize you're not alone as you sit in your bedroom massaging your calves after a long day of playing tug-of-war with grandpa Joe in the hospital.",
    "You shouldn't feel so responsible. You tried. You did something. That's what counts.",
    "You talkin to me?",
    "You think I'm funny? Like I'm a clown? I amuse you?",
    "You will only survive if you keep the fire going! I can hear thunder in the distance.",
    "You're gonna need a bigger boat",
    "You're good at english when you know the difference between a man eating chicken and a man-eating chicken.",
    "You're unsure whether or not to trust me, but be very thankful that you wore a turtle neck.",
    "You've got to ask yourself one question: do I feel lucky? well, do ya, punk?",
    "Your girlfriend bought your favorite cookie crisp cereal, but I drank all the milk.",
    "{name} The little hand says it's time to Rock and Roll!",
]
