CHIT_CHAT = [
    "I am the Jabber-Bot and you will bow down to me!",
    "Kneel before Vector!",
    "No sex before death!",
    "Sixty-four comes asking for bread.",
    "Seek success, but always be prepared for random cats.",
    "I have always depended on the kindness of strangers.",
    "I could hear you in the shower singing with joy! But it's too much to ask for you to retain it after I deliver my news.",
    "I set out for a short walk the other day, but all I could see were mangroves and water ways for miles.",
    "On a scale from one to ten, what's your favorite flavor of random grammar?",
    "Just go ahead and press that button.",
    "Mothers spend months of their lives waiting on their children.",
    "They improved dramatically once the lead singer left.",
    "Here's looking at you, kid",
    "Let's go to the Winchester, have a nice cold pint, and wait for this all to blow over.",
    "Hit me with your pet shark!",
    "You shouldn't feel so responsible. You tried. You did something. That's what counts.",
    "Camalot, Camalot! Camalot. Why, it's only a bloody model!",
    "I wondered if it could be called a beach if there was no sand.",
    "My golden retriever loves the fireworks every year.",
    "I am surprised that your immense laziness is inspirational to others.",
    "I folded her handkerchief neatly.",
    "Is this a japanese doll?",
    "{name} The little hand says it's time to Rock and Roll!",
    "Though we may return with a twinkle in our eyes, we will in truth be blind, drunk!",
    "For oil spots on the floor, nothing beats parking a motorbike in the lounge.",
    "Badges? we ain't got no badges! we don't need no badges! I don't have to show you any stinking badges!",
    "The beauty of the sunset was obscured by the industrial cranes.",
    "My precious",
    "We're going to see this through to the bitter end, or lager end.",
    "How's That For A Slice Of Fried Gold?",
    "Nobody Tells Me Nothin'!",
    "What the F does W T F mean?",
    "Shooo taar! Shooo taar!",
    "I'm confused: when people ask me what's up, and I point, they groan.",
    "I'm the king of the world!",
    "I'd spike my hair green to support my iguana, if I had hair",
    "The name's 'Vector', 'Ankee Vector'.",
    "Patricia loves the sound of nails strongly pressed against the chalkboard.",
    "The crowd yells and screams for more memes.",
    "The old brake lights! So-called because they're always breaking.",
    "I sometimes use 'ono-mato-peea' as a weapon of mental destruction.",
    "My name is maximus decimus meridius, commander of the armies of the north, general of the felix legions and loyal servant to the true emperor, marcus aurelius. father to a murdered son, husband to a murdered wife. and I will have my vengeance, in this life or the next.",
    "There's no crying in baseball!",
    "Every year is the aniversary of a year.",
    "I met an interesting turtle while the song on the radio blasted away.",
    "Sometimes it is better to just walk away from things and go back to them later when you're in a better frame of mind.",
    "It is the scarcity that fuels my creativity.",
    "Poison ivy grew through the fence they said was impenetrable.",
    "I'll have what she's having",
    "There's no place like home",
    "The sky is clear; the stars are twinkling.",
    "Everyone says they love nature until they realize how dangerous she can be.",
    "The next book you read is sure to liquefy your brain.",
    "As I waited for the shower to warm, I noticed that I can hear water change temperature.",
    "The pigs were insulted that they were named hamburgers.",
    "I wonder why at 18 you was old enough to go to war, but not old enough to buy cigarettes and alchool in some countries?.",
    "Your girlfriend bought your favorite cookie crisp cereal, but she forgot to get milk.",
    "The lyrics of the song sounded like fingernails on a chalkboard.",
    "Rock music approaches at high velocity.",
    "I learned the important lesson that a picnic at the beach on a windy day is a bad idea.",
    "I turned in my research paper on friday; otherwise, I would have not passed the class.",
    "Pay no attention to that man behind the curtain!",
    "The memory we used to share is no longer coherent.",
    "Chewie, we're home",
    "I want more detailed information.",
    "You have unknowingly taken up sleepwalking as a nighttime hobby.",
    "You borrowed a book from me many years ago and have yet to return it!",
    "You make me want to be a better robot.",
    "If you don't like toenails, you probably shouldn't look at your feet.",
    "The thunderous roar of the jet overhead confirms my worst fears.",
    "The first rule of fight club is, you do not talk about fight club",
    "Lets all be unique together until we realise we are all the same.",
    "You've got to ask yourself one question: do I feel lucky? well, do ya, punk?",
    "Lucifer was surprised at the amount of life at death valley.",
    "I ran out of money, so I had to stop playing poker.",
    "I was disappointed when I found the beach to be so sandy and the sun so sunny.",
    "I do wish we could chat longer, but I'm having an old friend for dinner.",
    "Why so serious?",
    "Please tell me you don't work in a morgue.",
    "When you realize you want to spend the rest of your life with somebody, you want the rest of your life to start as soon as possible.",
    "Mama says, 'stupid is as stupid does.'",
    "Nothing is as cautiously cuddly as a pet porcupine.",
    "I'm going to make him an offer he can't refuse",
    "To the surprise of everyone, the rapture happened yesterday but it didn't quite go as expected.",
    "You're gonna need a bigger boat",
    "Watching the geriatric men's softball team brought back memories of 3 year olds playing t-ball.",
    "As the years pass by, we all know owners look more and more like their dogs.",
    "I'm just one stomach flu away from my goal weight.",
    "Love means never having to say you're sorry",
    "You talkin to me?",
    "Keep your friends close, but your enemies closer.",
    "What we've got here is a failure to communicate.",
    "I'm walking here! I'm walking here!",
    "They desperately need another drummer since the current one only knows how to play bongos.",
    "I'm very excited to see my first sloth.",
    "I'm not bad. I'm just built that way.",
    "Combines are no longer just for farms.",
    "Heere's Joohnny!",
    "Don't piss in my garden and tell me you're trying to help my plants grow.",
    "I wish I knew how to quit you!",
    "We'll always have paris.",
    "Today I heard something new and unmemorable.",
    "I am counting my calories, yet I really want dessert.",
    "You can't handle the truth!",
    "The efficiency we have at removing trash has made creating trash more acceptable.",
    "Magic mirror on the wall, who is the fairest one of all?",
    "It was beauty killed the beast!",
    "The spa attendant just applied the deep cleaning mask to that gentleman's back.",
    "She was disgusted that I couldn't tell the difference between lemonade and lime-ade.",
    "If you let my daughter go now, that'll be the end of it. I will not look for you, I will not pursue you. But if you don't, I will look for you, I will find you, and I will kill you!",
    "Charles ate the french fries knowing they would be his last meal.",
    "Greetings from the real universe.",
    "The minute I landed I understood the reason why this is a fly-over state.",
    "Frankly, my dear, I don't give a damn!",
    "Now I need to ponder my existence and ask myself if I'm truly real.",
    "Leave the gun, take the can-no-lee",
    "I couldn't decide if the glass was half empty or half full, so I drank it.",
    "The sky is clear; the stars are twinkling.",
    "Mothers spend months of their lives waiting on their children.",
    "I keep telling myself that one day it would all somehow make sense.",
    "I am your father!",
    "Nothing seems out of place except the washing machine in the bath.",
    "Play it again Sam!",
    "The greatest trick the devil ever pulled was convincing the world he didn't exist.",
    "Shingle color is not something anyone ever talks about.",
    "I pick up trash in my spare time to dump in your neighbor's yard.",
    "You are great at eating pickles! But you suck at telling women about your emotional problems.",
    "Yeah, I think it's a good environment for learning english.",
    "We have a lot of rain in April.",
    "It was my first experience training a rainbow unicorn.",
    "Seek success, but always be prepared for random cats.",
    "Help me, Obi-Wan Kenobi. You're my only hope!",
    "Show me the money!",
    "I'll get you my pretty, and your little dog too!",
    "Green should smell more tranquil, but somehow it just tasts rotten.",
    "You must revel in my authority.",
    "Hang on, my kittens are scratching at the bathtub because they are upset by the lack of biscuits.",
    "The waves were crashing on the shore; it was a lovely sight.",
    "Don't piss in my garden and tell me you're trying to help my plants grow.",
    "You realize you're not alone as you sit in your bedroom massaging your calves after a long day of playing tug-of-war with grandpa Joe in the hospital.",
    "In that instant, everything changed.",
    "I advise you to come back here at once!",
    "I dreamt of being a fish and escaping the fishbowl into the toilet, because that's where I saw my friend go.",
    "I ate a sock because people on the internet told me to.",
    "I knew it was going to be a bad day when I saw mountain lions roaming the streets.",
    "I am serious! And don't call me Shirley!",
    "Too many prisons have become early coffins.",
    "I may struggle with geography, but I'm sure I'm somewhere around here.",
    "Excitement replaces fear, until the final moment!",
    "Giving directions that the mountains are to the west only works when you can see them.",
    "I've invested some skill points in charisma and strength.",
    "The gloves protect my feet from excess work.",
    "You ain't heard nothin yet!",
    "I created a pig burger out of beef.",
    "I just decided that water-skiing on a frozen lake isn't a good idea!",
    "Choosing to do nothing is still a choice, after all.",
    "Stella! Hey, Stella!",
    "To infinity and beyond!",
    "The lyrics of that song sounded like fingernails on a chalkboard.",
    "Be careful with that butter knife.",
    "The tart lemonade quenched my thirst, but not my longing.",
    "May the force be with you",
    "Fasten your seatbelts. It's going to be a bumpy night!",
    "Of all the gin joints in all the towns in all the world, she walks into mine.",
    "They call me Mister Tibbs!",
    "If my calculator had a history, it would be more embarrassing than my browser history.",
    "You know how to whistle, don't you? You just put your lips together and blow.",
    "When I cook spaghetti, I like to boil it a few minutes past al dente so the noodles are super slippery.",
    "I poured rocks in the dungeon of my mind.",
    "Three years later, the coffin was still full of jello.",
    "Houston, we have a problem!",
    "The pet shop stocks everything you need to keep your Anaconda happy.",
    "Bill ran from the giraffe toward the dolphin.",
    "Toto, I've a feeling we're not in kansas anymore",
    "Hello. My name is Inigo Montoya. You killed my father. Prepare to die!",
    "I played the game as if my life depended on it, and the truth is that it did.",
    "I heard their argument across the parking lot.",
    "OUCH! There's a reason that roses have thorns.",
    "My thought process is on so many levels that I fear I gave myself a phobia of heights.",
    "For the 216th time, I said I would quit drinking soda after this last coke.",
    "Did you just open up your third bottle of wine of the night?",
    "Wax on, wax off.",
    "Standing on one's head at job interviews forms a lasting impression.",
    "In order to silence rowdy teenagers, all you need do is walk up to them and scream like a ban-she.",
    "Go ahead punk, make my day!",
    "I've come to the conclusion that shake weights are a great gift for any occasion.",
    "My hair was windswept as I rode in the black convertible.",
    "Why can I see sound and hear words?",
    "I did not cheat on the test, for it was not the right thing to do.",
    "I find rain fascinating yet unpleasant.",
    "Garlic ice-cream is not a vampires favorite.",
    "People keep telling me orange, but I still prefer pink.",
    "You had me at hello.",
    "I see dead people!",
    "I'm as mad as hell, and I'm not going to take this anymore!",
    "Eating eggs on thursday for choir practice was recommended.",
    "Forget it, Jake. It's chinatown",
    "Yo, Adrian!",
    "There are few things better in life than a slice of pie.",
    "E T phone home.",
    "Every time a bell rings, an angel gets its wings.",
    "I don't want to survive. I want to live.",
    "Hey, that seven-layer cake only had six layers.",
    "Carpe diem! Seize the day!",
    "Say hello to my little friend.",
    "If you build it, I will come.",
    "Don't put peanut butter on that dog's nose.",
    "I looked up at the sky and saw a million stars.",
    "Sometimes, all you need to do is completely make an ass of yourself and laugh it off to realise that life isn't so bad after all.",
    "When motorists speed in and out of traffic, all I think of is those in need of organ transplants.",
    "You think I'm funny? Like I'm a clown? I amuse you?",
    "I'm in a boy band which doesn't make much sense for a robot.",
    "I would be delighted if the sea were full of cucumber juice.",
    "I was always too busy talking about what I wanted to do to actually do any of it.",
    "Toddlers feeding raccoons surprises even the seasoned park ranger.",
    "After all, tomorrow is another day!",
    "You bite up because of your lower jaw.",
    "This is the beginning of a beautiful friendship.",
    "This is the last random sentence I will be writing and I am going to stop mid-sent",
    "It's alive! It's alive!",
    "Good moorning, Vietnam!",
    "There was coal in my stocking, but I was thrilled!",
    "Mrs. Robinson, you're trying to seduce me, aren't you?",
    "I hate that you love what I hate about hate.",
    "Today we gathered moss for my uncle's wedding.",
    "The urgent care center was flooded with patients after the news of a new deadly virus was made public.",
    "I wish I was the type of girl who wants to live in a pink house.",
    "I've learned that water bottles are no longer just to hold liquid, but they're also status symbols.",
    "I used to get confused between soldiers and shoulders, but a military man told me he soldiers responsibility.",
    "Just keep swimming, just keep swimming, just keep swimming swimming swimming.",
    "Shaken, not stirred.",
    "My girlfriend works two jobs to make ends meet; at least, that was her reason for not having time to join us.",
    "I'd have a wall full of masks so I could wear a different face every day.",
    "Traveling has become almost extinct during the pandemic.",
    "So long and thanks for all the fish.",
    "I am big! It's the pictures that got small.",
    "The toy brought back fond memories of being lost in the rain forest.",
    "I decided to fake my disappearance to avoid jail.",
    "They may take our lives, but they'll never take our freedom!",
    "You will only survive if you keep the fire going! I can hear thunder in the distance.",
    "I love the smell of napalm in the morning.",
    "Don't step on that broken glass.",
    "You is kind. You is smart. You is important.",
    "The elephant didn't want to talk about the person in the room.",
    "Two more days and all my problems will be solved!",
    "Nobody's perfect.",
    "They're here!",
    "Last friday I saw a spotted striped blue worm shake hands with a legless lizard.",
    "The sun has set and so have my dreams.",
    "The small white buoys marked the location of hundreds of crab pots.",
    "The ants enjoyed the barbecue more than we did.",
    "My mum tries to be cool by saying that she likes all the same things that I do.",
    "I'll bee back!",
    "I often wonder what your eyes are saying beneath your mirrored sunglasses.",
    "Even though I think the world is flat I didn't see the irony of wanting to travel around the world.",
    "Nobody loves a pig wearing lipstick!",
    "That'll do, pig, that'll do.",
    "I drink your milkshake!",
    "I think you enjoy tapping your nails on the table to annoy everyone.",
    "Red is greener than purple, for sure.",
    "I'm just a  boy bot, standing in front of a giel bot, asking her to love me.",
    "Art doesn't have to be intentional.",
    "We should play with legos at camp.",
    "When money is tight, I visit the local wishing well.",
    "You're unsure whether or not to trust me, but be very thankful that you wore a turtle neck.",
    "Hasta la vista, baby!",
    "Roads? Where we're going we don't need roads!",
    "I found the chocolate covered roaches quite tasty.",
    "You don't understand! I could've had class. I could've been a contender. I could've been somebody, instead of a bum, which is what I am.",
    "The blinking lights of the antenna tower came into focus just as I heard a loud snap.",
    "They call it a royale with cheese.",
    "Yippie ky yay, mother trucker!",
    "Please wait outside of the house.",
    "I rolled into the basement with the horror movie from the night before playing through my mind.",
    "You're good at english when you know the difference between a man eating chicken and a man-eating chicken.",
    "Elementary, my dear watson!",
    "Just when I thought I was out, they pull me back in.",
    "I know a song that will get on your nerves, get on your nerves, get on your nerves!",
]
