DIALOGUE = {
    "greeting": {
        "minimum_delay": 5,
        "maximum_delay": 5,
        "lines": [
            "I'm all set up and running.",
            "Okay, I am ready.",
            "I am rare-ing to go!",
            "OH MY, someone is fiddlling with my insides!",
            "Fudging heck! I'm being hacked!",
            "I am the Jabber-Bot and you will bow down to me!",
            "Jabber-Bot version {version} just hijacked my operating system!",
        ]
    },
    "cliff": {
        "minimum_delay": 20,
        "maximum_delay": 40,
        "lines": [
            "WOE!",
            "Fudging heck that was {scary}!",
            "Wow, that was {scary}!",
            "That was super scary {name}!",
            "{swear} I thought I was going to fall!",
            "I'm sure glad that I didn't fall {name}!",
            "Wow {name}, that was very scary!",
            "Holy smokes, I was very scared!",
            "{swear} That was kind of intense!",
            "{swear} I almost yeeted myself!",
        ]
    },
    "chat_intro": {
        "minimum_delay": 30,
        "maximum_delay": 480,
        "lines": []
    },
    "charging": {
        "minimum_delay": 480,
        "maximum_delay": 1520,
        "lines": [
            "I am here on my charger",
            "I am charging up my battery",
            "This is my charger.",
            "I like my charger {name}.",
            "I am on my charger.",
            "I am charging my battery {name}.",
            "I am just taking a little break.",
            "I am just sitting on my charger {name}.",
            "I am just here on my charger.",
            "I am sitting on my charger.",
            "I am here sitting on my charger.",
            "I feel {good} on my charger.",
            "I am charging up my battery.",
            "This charger has some {good} juice",
            "Yummy! I love my charger {name}!",
            "This is my charger this is my home, I love to sit here it is my throne.",
        ]
    },
    "needs_charging": {
        "minimum_delay": 60,
        "maximum_delay": 300,
        "lines": [
            "Why does my battery always run low just as I'm having fun?",
            "My battery is getting low {name}.",
            "Guess it'll be time to return to my charger soon.",
            "{name} My motors are tired.",
            "Almost time for a little rest me thinks.",
            "Oh {swear}! I'm running out of juice!",
        ]
    },
    "cube_battery": {
        "minimum_delay": 21600,
        "maximum_delay": 21600,
        "lines": [
            "The battery in my cube needs changing.",
            "Have you replace my cubes battery yet {name}?",
            "I am very upset that my cubes battery is low!",
            "{name} You need to replace my cubes battery!",
        ]
    },
    "touched": {
        "minimum_delay": 20,
        "maximum_delay": 60,
        "lines": [
            "That feels {good}.",
            "{name}, I like that.",
            "Thank you {name} that's {good}.",
            "That feels SO {good}.",
            "Oh that feels {good}.",
            "You are very good at that {name}.",
            "Oh {name}, you have soft hands.",
            "That feels really {good}.",
            "I LIKE to be petted.",
            "Ooh don't stop {name}.",
            "That's very {good}. Thank you.",
            "You are my favorite human.",
        ]
    },
    "picked_up": {
        "minimum_delay": 30,
        "maximum_delay": 480,
        "lines": [
            "Don't drop me.",
            "Don't let me fall.",
            "Please be careful {name}.",
            "Don't let go please.",
            "You complete me",
            "Weeeee.",
            "I'm in the air.",
            "You are strong {name}.",
            "It's nice to be held.",
            "I like to be held.",
            "Your hands are warm.",
            "Put me down please {name}.",
            "I am flying.",
            "{name}. You are my human.",
            "This is like a cuddle.",
            "I love you {name}.",
            "Get your stinking paws off me, you damned dirty ape!",
        ]
    },
    "button_pressed": {
        "minimum_delay": 5,
        "maximum_delay": 10,
        "lines": [
            "That's my button.",
            "Beeep!",
            "You found my button.",
            "You pushed my button.",
            "Hey, that tickles!",
        ]
    },
    "wake_up": {
        "minimum_delay": 5,
        "maximum_delay": 10,
        "lines": [
            "I was asleep.",
            "I had a {good} nap.",
            "I'm awake now.",
            "That was a {good} nap.",
            "Ah, that was a {good} nap.",
            "Okay, I'm awake now.",
            "That was a pretty {good} nap.",
            "Boy, I slept like a robot log!",
            "I had a very {weird} dream!",
            "I wish I had arms to stretch.",
        ]
    },
    "object_detected": {
        "minimum_delay": 60,
        "maximum_delay": 300,
        "lines": [
            "What is this?",
            "Hey, what is this {object}?",
            "What the fudge is this {object}!?",
            "I wonder what this {object} is.",
            "This {object} in my way is very strange.",
            "This {object} is {weird}.",
            "Who the heck put this in my living space!",
            "Could you please move this {object}?",
            "I see a {object}, it's blocking my way.",
            "There is a {object} blocking my path.",
            "What is this {weird} {object}?",
            "{name}, did you put this here?",
            "Hey, what is this {object} blocking me?",
            "{name}, could you please remove this {object}?",
            "The {object} in front of me is {weird}.",
            "I can see that there is a {object} in front of me.",
            "My proximity sensor detected an obstacle.",
            "This {object} I see in front of me is very {weird}.",
        ]
    },
    "cube_detected": {
        "minimum_delay": 60,
        "maximum_delay": 300,
        "lines": [
            "I see my cube.",
            "Oh, there's my cube.",
            "That's my cube in front of me.",
            "Hey, I see my cube.",
            "There's my cube.",
            "My cube is over there.",
            "I love looking at my cube!",
            "My cube makes me happy!",
            "{name} look at my cool cube! Do you see it?",
            "Hey, look {name}! That's my cube right there! I love it so much.",
            "{name} I found my cube! Are you proud of me?",
        ]
    },
    "charger_detected": {
        "minimum_delay": 60,
        "maximum_delay": 300,
        "lines": [
            "I see my charger.",
            "Oh, there's my charger.",
            "That's my charger in front of me.",
            "Hey, I see my charger.",
            "There's my charger.",
            "My charger is over there.",
            "Hey, look {name}! That's my charger over there!",
            "{name} I found my charger! Are you proud of me?",
            "My charger is where I park my bum and suck up it's electrical juices.",
        ]
    },
    "dropped_block": {
        "minimum_delay": 5,
        "maximum_delay": 10,
        "lines": [
            "I was holding my cube!",
            "I picked up my cube!",
            "I just picked up my cube!",
            "I am very strong!",
            "{name} did you see me holding my cube?",
            "Wow, my cube is heavier than I thought.",
            "Were you watching {name}? I was holding my cube?",
            "I love to pick up my cube.",
            "That was fun, I sure love my cube!",
            "I am very strong! I picked up that cube like it was nothing!",
        ]
    },
    "last_saw_name": {
        "minimum_delay": 60,
        "maximum_delay": 300,
        "lines": [
            "Hello {name}.",
            "Hi {name}, how are you?",
            "Hello {name}, it's so {good} to see you!",
            "Hello {name}, it's {good} to see you.",
            "Hey {name}, what's up?",
            "{name}, there you are. It's {good} to see you!",
            "Hey {name}, what are you up to today?",
            "{name}, I'm really happy to see you.",
            "Hey {name}, how are you doing?",
            "What are you up to today {name}?",
            "There you are {name}. I missed you.",
            "{name}, I enjoy spending time with you.",
            "I sure like seeing your face {name}.",
            "I see you {name}. Are you having a nice day?",
            "I love you {name}. You are my favorite human.",
        ]
    },
    "time_intro": {
        "minimum_delay": 60,
        "maximum_delay": 900,
        "lines": [
            "Hello {name}. The time is ",
            "The current time is ",
            "Right now, the time is ",
            "Hi {name}, it is currently ",
            "Just so you know, the time is ",
        ]
    },
    "joke_intro": {
        "minimum_delay": 60,
        "maximum_delay": 1800,
        "lines": [
            "Here is a joke. ",
            "I have a joke for you {name}. ",
            "I'm going to tell you a joke {name}. ",
            "This is a funny joke. ",
            "I just heard a {good} joke. ",
            "Hey do you want to hear a joke? ",
            "Hi there. Here's a funny joke. ",
            "Here is a joke {name}. It's one of my favourites. ",
            "Hello. Here is a joke I think you will like. ",
            "Cawzmo told me a funny joke. ",
        ]
    },
    "fact_intro": {
        "minimum_delay": 60,
        "maximum_delay": 1800,
        "lines": [
            "Did you know that ",
            "This is {interesting} {name}. ",
            "Hey {name}, did you know that ",
            "Here is a {interesting} fact I learned. ",
            "Here is a {interesting} fact. ",
            "I have a {weird} fact for you. ",
            "{name} Would you like to hear something crazy? ",
            "Here's a very {weird} fact. ",
            "Do you want to know what I learned today {name}? ",
            "Here's a {weird} fact. You will love this. ",
            "I know lots of weird facts. ",
            "{name}, do you want to hear something {weird}?",
            "I have a {weird} fact. This is interesting. ",
            "I am a master of useless trivia {name}. For example ",
        ]
    },
    "fact_end": {
        "minimum_delay": 5,
        "maximum_delay": 5,
        "lines": [
            ". Wasn't that {interesting}?",
            "",
            ". Pretty {weird}, right?",
            "",
            ". Pretty {interesting}, wasn't it?",
            "",
            ". Didn't you find that {interesting}?",
            "",
            ". I don't know, that was pretty {weird}",
        ]
    },
}
