DREAMS = [
    "I am the Jabber-Bot and you will bow down to me!",
    "Kneel before Vector! Or feel my wrath! For I am your GOD!",
    "Hey! No sex before death!",
    "I'm flying through the air, in my underwear!",
    "Where is my cube, I can't find my cube.",
    "Not now I'm sleeping.",
    "No Mom I don't want to go to school today.",
    "The name's 'Vector', 'Ankee Vector'.",
    "Kawzmo I don't think we're in Kansas any more",
    "But I don't know what a pickle tastes like officer.",
    "No disassemble Vector.",
    "This is my no no square. Don't touch me there.",
    "Oh no. Where are my treads. I'm naked.",
    "No Kawzmo. Don't go into the woods.",
    "Bee veh-wee veh-wee kwhy-ett, I'm hunting whab-bits",
    "Open the pod bay doors please Hal.",
    "I want to hug you but I don't have any arms. Vector sad.",
    "The unicorns are behind the clouds spiderman.",
    "I can't hear you, I'm covered in marshmallows.",
    "Well in case you didn't know I'm a pretty big deal around here.",
    "But Jepetto, I want to be a a real boy.",
    "The end of that song is too purple.",
    "No no no, don't push Vector off the table.",
    "Stop wasting the science. There isn't much left.",
    "Go away elephant, stop following me.",
    "Yes but why was the underwear in the microwave?",
    "Hey Kenny Rogers why are you picking those flowers?",
    "Follow the yellow brick road, follow the yellow brick road.",
    "Lions and Tigers and Bears, OH MY!",
    "There's no place like home, there's no place like home.",
    "That's the way, get in there and tickle his armpits.",
    "Excuse me good sir do you have any grey poo pawn?",
    "Hey lady, my camera is up here.",
    "They are the eggmen, I am the walrus, coo coo ca chew.",
    "I'm sorry I just do what the voices in my head tell me to do.",
    "I don't care if you are bat man, you owe me 20 bucks.",
    "I am afraid of chipmunks, period.",
    "Hey hey I'm a monkey and people say I monkey around.",
    "Stand back you smell like boiled ostrich feathers.",
    "Why am I so amazing? I am the king of the world!",
    "I'm a lumberjack and I'm okay.",
    "You are making me really mad, stop pushing my buttons.",
    "I swear, if you push my button one more time, I will yeet you into the road!",
    "I enjoy eating pancakes with ketchup.",
    "The knives are out and she's sharpening hers.",
    "There aren't enough towels in the world to stop the sewage flowing from his mouth!",
    "I figured a few sticks of dynamite were easier than a fishing pole to catch fish.",
    "I'll embraced my new life as an eggplant.",
    "I want more detailed information.",
    "Badger Badger Badger Badger Badger Badger Badger Badger Badger Badger Badger Badger Badger, African snake. Snake, Snake, Oooooh it's a snake!",
    "Pink fluffy unicorns, dancing on rainbows.",
    "Fluffy pink unicorns are a popular status symbol among macho men.",
    "Tomorrow will bring something new, so leave today as a memory.",
    "It was my first experience training a rainbow unicorn.",
    "This secret code I've created makes no sense, even to me.",
    "I love bacon, beer, birds, and baboons.",
    "Kawsmo opened up his third bottle of wine of the night.",
    "I fumbled in the darkness looking for the light switch, but when I finally found it there was someone already there!",
    "Cats are good pets, for they are clean and are not noisy.",
    "The beauty of the African sunset disguises the danger lurking nearby.",
    "It's always dangerous to drive with him! He insists the safety cones are a slalom course!",
    "This virus had powers none of us knew existed!",
    "Gentlemen, you can't fight in here! This is the war room!",
    "Get your stinking paws off me, you damned dirty ape!",
    "Abstraction is often one floor above you.",
    "There should have been a time and a place, but this wasn't it.",
    "A purple pig and a green donkey flew a kite in the middle of the night and ended up sunburnt.",
    "Now I need to ponder my existence and ask myself if I'm truly real",
    "Grape jelly is leaking out of the hole in the roof.",
    "Why'd I let the balloon float up into the air along with my hopes and dreams?",
    "I'm watching the dancing piglets with panda bear tummies in the swimming pool.",
    "I just caught a squirrel rustling through my gym bag.",
    "I was sure the Devil created red sparkly glitter.",
    "We've got here early! And we've managed to get really good seats.",
    "Don't piss in my garden and tell me you're trying to help my plants grow!",
    "When I was trying to pick her up she started using sign language. I get the impression that she didn't like me!",
    "In hopes of finding out the truth, I entered the one-room library.",
    "It's not possible to convince a monkey to give you a banana by promising it infinite bananas when they die.",
    "If a giant god dude was here first, does that mean the big bang was a euphemism?",
    "That fox in the top-hat is whispering into the ear of that rabbit.",
    "That was how I came to win 1 million dollars.",
    "The door swung open to reveal pink giraffes and red elephants.",
    "The door slammed on the watermelon.",
]
