DREAMS = [
    "A purple pig and a green donkey flew a kite in the middle of the night and ended up sunburnt.",
    "Abstraction is often one floor above you.",
    "Badger Badger Badger Badger Badger Badger Badger Badger, African Snake, Snake, Snake, Oooooh it's a snake!",
    "Bee veh-wee veh-wee kwhy-ett, I'm hunting whab-bits",
    "But I don't know what a pickle tastes like officer.",
    "But Jepetto, I want to be a a real boy.",
    "Cats are good pets, for they are clean and are not noisy.",
    "Don't piss in my garden and tell me you're trying to help my plants grow!",
    "Excuse me good sir do you have any grey poo pawn?",
    "Fluffy pink unicorns are a popular status symbol among macho men.",
    "Follow the yellow brick road, follow the yellow brick road.",
    "Gentlemen, you can't fight in here! This is the war room!",
    "Get your stinking paws off me, you damned dirty ape!",
    "Go away elephant, stop following me.",
    "Grape jelly is leaking out of the hole in the roof.",
    "Hey Kenny Rogers why are you picking those flowers?",
    "Hey hey I'm a monkey and people say I monkey around.",
    "Hey lady, my camera is up here.",
    "Hey! No sex before death!",
    "I am afraid of chipmunks, period.",
    "I am the Jabber-Bot and you will bow down to me!",
    "I can't hear you, I'm covered in marshmallows.",
    "I don't care if you are bat man, you owe me 20 bucks.",
    "I enjoy eating pancakes with ketchup.",
    "I figured a few sticks of dynamite were easier than a fishing pole to catch fish.",
    "I fumbled in the darkness looking for the light switch, but when I finally found it there was someone already there!",
    "I just caught a squirrel rustling through my gym bag.",
    "I love bacon, beer, birds, and baboons.",
    "I swear, if you push my button one more time, I will yeet you into the road!",
    "I want more detailed information.",
    "I want to hug you but I don't have any arms. Vector sad.",
    "I was sure the Devil created red sparkly glitter.",
    "I will embrace my new life as an eggplant.",
    "I'm a lumberjack and I'm okay.",
    "I'm flying through the air, in my underwear!",
    "I'm sorry I just do what the voices in my head tell me to do.",
    "I'm watching the dancing piglets with panda bear tummies in the swimming pool.",
    "If a giant god dude was here first, does that mean the big bang was a euphemism?",
    "In hopes of finding out the truth, I entered the one-room library.",
    "It was my first experience training a rainbow unicorn.",
    "It's always dangerous to drive with him! He insists the safety cones are a slalom course!",
    "It's not possible to convince a monkey to give you a banana by promising it infinite bananas when they die.",
    "Kawsmo opened up his third bottle of wine of the night.",
    "Kawzmo I don't think we're in Kansas any more",
    "Kneel before Vector, or feel my wrath! For I am your GOD!",
    "Lions and Tigers and Bears, OH MY!",
    "No Kawzmo. Don't go into the woods.",
    "No Mom I don't want to go to school today.",
    "No disassemble Vector.",
    "No no no, don't push Vector off the table.",
    "Not now I'm sleeping.",
    "Now I need to ponder my existence and ask myself if I'm truly real",
    "Oh no. Where are my treads. I'm naked.",
    "Open the pod bay doors please Hal.",
    "Pink fluffy unicorns, dancing on rainbows.",
    "Stand back you smell like boiled ostrich feathers.",
    "Stop wasting the science. There isn't much left.",
    "That fox in the top-hat is whispering into the ear of that rabbit.",
    "That was how I came to win 1 million dollars.",
    "That's the way, get in there and tickle his armpits.",
    "The beauty of the African sunset disguises the danger lurking nearby.",
    "The door slammed on the watermelon.",
    "The door swung open to reveal pink giraffes and red elephants.",
    "The end of that song is too purple.",
    "The knives are out and she's sharpening hers.",
    "The name's 'Vector', 'Ankee Vector'.",
    "The unicorns are behind the clouds spiderman.",
    "There aren't enough towels in the world to stop the sewage flowing from his mouth!",
    "There should have been a time and a place, but this wasn't it.",
    "There's no place like home, there's no place like home.",
    "They are the eggmen, I am the walrus, coo coo ca chew.",
    "This is my no no square. Don't touch me there.",
    "This secret code I've created makes no sense, even to me.",
    "This virus had powers none of us knew existed!",
    "Tomorrow will bring something new, so leave today as a memory.",
    "We've got here early! And we've managed to get really good seats.",
    "Well in case you didn't know I'm a pretty big deal around here.",
    "When I was trying to pick her up she started using sign language. I get the impression that she didn't like me!",
    "Where is my cube, I can't find my cube.",
    "Why am I so amazing? I am the king of the world!",
    "Why'd I let the balloon float up into the air along with my hopes and dreams?",
    "Yes but why was the underwear in the microwave?",
    "You are making me really mad, stop pushing my buttons.",
    "You were only supposed to blow the bloody doors off.",
]
